version: '3'
volumes:
  postgresdb:
  grafana:
services:
  # server:
  #   build:
  #     dockerfile: ./server/Dockerfile.dev
  #     context: ./
  #   volumes:
  #     - ./server:/code/server
  #   ports:
  #     - 6603:80
  #   restart: always
  #   command: ../node_modules/.bin/ts-node-dev --transpile-only ./index.ts
  #   # command: tail -f /dev/null
  #   env_file:
  #     - ./server/.dev.env
  grafana:
    restart: always
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 6604:3000
  # zigbee2mqttAssistant:
  #   image: carldebilly/zigbee2mqttassistant
  #   container_name: zigbee2mqttAssistant
  #   environment:
  #     - Z2MA_SETTINGS__MQTTSERVER=verne
  #     - Z2MA_SETTINGS__MQTTUSERNAME=""
  #     - Z2MA_SETTINGS__MQTTPASSWORD=""
  #     - Z2MA_SETTINGS__MQTTPORT=1883
  #     - Z2MA_SETTINGS__BASETOPIC=zigbee2mqtt2
  #     - TZ=Asia/Makassar
  #   ports:
  #     - 6605:80
  #   restart: always
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=aha
      - POSTGRES_PASSWORD=ahapassword
      - POSTGRES_DB=aha
    ports:
      - '6602:5432'
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
    volumes:
      - postgresdb:/var/lib/postgresql/data
  verne:
    image: vernemq/vernemq
    restart: always
    ports:
      - 6601:8080
      - 6600:1883
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqttdata:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Makassar
