version: '3'
volumes:
  postgresdb:
services:
  server:
    build:
      dockerfile: ./Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/code/server
    ports:
      - 6603:80
    restart: always
    command: ./node_modules/.bin/ts-node-dev --transpile-only ./index.ts
    # command: tail -f /dev/null
    env_file:
      - ./server/.dev.env
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=aha
  #     - POSTGRES_PASSWORD=ahapassword
  #     - POSTGRES_DB=aha
  #   ports:
  #     - '6604:5432'
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '1m'
  #   volumes:
  #     - postgresdb:/var/lib/postgresql/data
