version: '3'

services:
  server:
    build:
      dockerfile: ./Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/code/server
    ports:
      - 6603:80
    restart: always
    command: ./node_modules/.bin/ts-node-dev --transpile-only ./index.ts
    # command: tail -f /dev/null
    env_file:
      - ./server/.dev.env
