{
 "title": "Aha",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct on (device.id)\n TO_CHAR(AGE(now(), MAX(event.\"createdAt\")),'HH24:MI:SS') as \"lastSeen\" ,concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\",device.id ) as device ,device.type,device.\"ieeeAddr\",device.\"modelId\"\nFROM\n  device\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\nLEFT JOIN event ON device.id =event.\"deviceId\"\nGROUP By device.id,location.name,\"deviceModel\".name"
    }
   ]
  },
  {
   "title": "Recent isAction",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(AGE(now(),event.\"createdAt\"),'HH24:MI:SS') AS \"time\",\n concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\",device.id ) as device\nFROM event\nLEFT JOIN device ON event.\"deviceId\" = device.id\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\nWHERE\n  $__timeFilter(event.\"createdAt\") AND\n  event.\"isAction\"=true\nORDER BY event.\"createdAt\" DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event.\"createdAt\" AS \"time\",\n concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\" ) as ddevice,\n 1 as value\nFROM event\nLEFT JOIN device ON event.\"deviceId\" = device.id\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\n\nWHERE\n  $__timeFilter(event.\"createdAt\") AND device.\"modelId\"='WXKG11LM'\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  event.\"createdAt\" AS \"time\",\n concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\" ) as ddevice,\n 2 as value\nFROM event\nLEFT JOIN device ON event.\"deviceId\" = device.id\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\n\nWHERE\n  $__timeFilter(event.\"createdAt\") AND device.\"modelId\"='WSDCGQ01LM'\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  event.\"createdAt\" AS \"time\",\n concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\" ) as ddevice,\n 0 as value\nFROM event\nLEFT JOIN device ON event.\"deviceId\" = device.id\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\n\nWHERE\n  $__timeFilter(event.\"createdAt\") AND device.\"modelId\"='ZNCZ02LM'\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  event.\"createdAt\" AS \"time\",\n concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\" ) as ddevice,\n 3 as value\nFROM event\nLEFT JOIN device ON event.\"deviceId\" = device.id\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\n\nWHERE\n  $__timeFilter(event.\"createdAt\") AND device.\"modelId\"='RTCGQ01LM'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Climate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  climate.\"createdAt\" AS \"time\",\n  humidity, temperature, concat_ws( '.', location.name, device.\"name\", \"deviceModel\".\"name\" ) as device\nFROM climate\nLEFT JOIN event ON (climate.\"eventId\" = event.id)\nLEFT JOIN device ON event.\"deviceId\" = device.id\nLEFT JOIN location ON device.\"locationId\" = location.id\nLEFT JOIN \"deviceModel\" ON device.\"modelId\" = \"deviceModel\".id\nWHERE\n  $__timeFilter(climate.\"createdAt\")\nORDER BY 1"
    }
   ]
  }
 ]
}