homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://verne'
  include_device_information: true
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  log_output:
    - console
  last_seen: ISO_8601_local
  elapsed: true
